In [1]:
import pandas as pd
import numpy as np

In [6]:
features = pd.read_csv(r'C:\Diploma\user_features_final.csv')

In [7]:
print(features.shape)
features.head()

(86929, 32)

,user_id,total_orders,avg_days_between_orders,max_days_between_orders,last_order_recency,active_days_count,order_frequency,avg_items_per_order,total_items,reorder_ratio,...,avg_order_hour,avg_order_dow,orders_weekend_ratio,orders_morning_ratio,orders_evening_ratio,favorite_department,favorite_department_ratio,favorite_aisle,favorite_aisle_ratio,top_5_products
0,2,14,14.902564,30.0,13.0,14,1.0,8.553846,1668,0.476923,...,10.441026,2.005128,0.000000,0.917949,0.000000,dairy eggs,0.246154,yogurt,0.215385,"['Chipotle Beef & Pork Realstick', 'Organic Ha..."
1,3,12,10.181818,21.0,15.0,12,1.0,4.443182,391,0.625000,...,16.352273,1.011364,0.522727,0.000000,0.215909,produce,0.431818,fresh fruits,0.215909,"['Vanilla Unsweetened Almond Milk', 'Organic A..."
2,7,20,12.757282,30.0,7.0,20,1.0,7.252427,1494,0.669903,...,13.631068,1.728155,0.427184,0.422330,0.315534,produce,0.276699,refrigerated,0.131068,"['Lactose Free Fat Free Milk', 'Mexican Coffee..."
3,13,12,6.925926,13.0,6.0,12,1.0,4.148148,336,0.641975,...,15.135802,3.098765,0.938272,0.296296,0.370370,dairy eggs,0.333333,fresh vegetables,0.160494,"['Half & Half', 'Whole Milk', 'Whole Wheat Pit..."
4,14,13,23.985714,30.0,7.0,13,1.0,11.080952,2327,0.323810,...,8.952381,4.076190,0.142857,0.800000,0.066667,pantry,0.242857,fresh vegetables,0.109524,"['80 Vodka Holiday Edition', 'Jalapeno Pepper..."

In [8]:
features.info()
features.isna().sum().sort_values(ascending=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86929 entries, 0 to 86928
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   user_id                    86929 non-null  int64
 1   total_orders               86929 non-null  int64
 2   avg_days_between_orders    86929 non-null  float64
 3   max_days_between_orders    86929 non-null  float64
 4   last_order_recency         86929 non-null  float64
 5   active_days_count          86929 non-null  int64
 6   order_frequency            86929 non-null  float64
 7   avg_items_per_order        86929 non-null  float64
 8   total_items                86929 non-null  int64
 9   reorder_ratio              86929 non-null  float64
 10  max_items_per_order        86929 non-null  int64
 11  min_items_per_order        86929 non-null  int64
 12  unique_products            86929 non-null  int64
 13  unique_departments         86929 non-null  int64
 14  unique_aisles              86929 non-null  int64
 15  top_department_ratio       86929 non-null  float64
 16  top_aisle_ratio            86929 non-null  float64
 17  reorder_product_variety    86929 non-null  int64
 18  most_active_dow            86929 non-null  int64
 19  most_active_hour           86929 non-null  int64
 20  dow_entropy                86929 non-null  float64
 21  hour_entropy               86929 non-null  float64
 22  avg_order_hour             86929 non-null  float64
 23  avg_order_dow              86929 non-null  float64
 24  orders_weekend_ratio       86929 non-null  float64
 25  orders_morning_ratio       86929 non-null  float64
 26  orders_evening_ratio       86929 non-null  float64
 27  favorite_department        86929 non-null  object
 28  favorite_department_ratio  86929 non-null  float64
 29  favorite_aisle             86929 non-null  object
 30  favorite_aisle_ratio       86929 non-null  float64
 31  top_5_products             86929 non-null  object
dtypes: float64(17), int64(12), object(3)
memory usage: 21.2+ MB

user_id                      0
total_orders                 0
avg_days_between_orders      0
max_days_between_orders      0
last_order_recency           0
active_days_count            0
order_frequency              0
avg_items_per_order          0
total_items                  0
reorder_ratio                0
max_items_per_order          0
min_items_per_order          0
unique_products              0
unique_departments           0
unique_aisles                0
top_department_ratio         0
top_aisle_ratio              0
reorder_product_variety      0
most_active_dow              0
most_active_hour             0
dow_entropy                  0
hour_entropy                 0
avg_order_hour               0
avg_order_dow                0
orders_weekend_ratio         0
orders_morning_ratio         0
orders_evening_ratio         0
favorite_department          0
favorite_department_ratio    0
favorite_aisle               0
favorite_aisle_ratio         0
top_5_products               0
dtype: int64

In [9]:
cols_to_drop = [
    'user_id',
    'most_active_dow',
    'most_active_hour',
    'favorite_department',
    'favorite_aisle',
    'top_5_products'
]

In [10]:
clustering_df = features.drop(columns=cols_to_drop, errors='ignore')
print(clustering_df.shape)

(86929, 26)

In [11]:
clustering_df.dtypes.value_counts()

float64    17
int64       9
Name: count, dtype: int64

In [12]:
clustering_df.describe().T[['mean', 'std', 'min', 'max']]

                                  mean          std        min            max
total_orders                 28.774068    18.680644  12.000000      99.000000
avg_days_between_orders      10.793917     4.341299   0.284016      28.076923
max_days_between_orders      26.490515     6.052823   2.000000      30.000000
last_order_recency           12.212311     9.209482   0.000000      30.000000
active_days_count            28.774068    18.680644  12.000000      99.000000
order_frequency               1.000000     0.000000   1.000000       1.000000
avg_items_per_order           6.693737     3.204102   1.000000      37.908343
total_items                2447.219075  3372.532342  12.000000  137664.000000
reorder_ratio                 0.590082     0.157336   0.014493       0.989529
max_items_per_order          20.760080    10.645057   1.000000     145.000000
min_items_per_order           1.000000     0.000000   1.000000       1.000000
unique_products             101.476653    65.670172   1.000000     726.000000
unique_departments           12.805600     3.279852   1.000000      21.000000
unique_aisles                38.057748    16.383243   1.000000     102.000000
top_department_ratio          0.360958     0.142401   0.095618       1.000000
top_aisle_ratio               0.197575     0.106360   0.041570       1.000000
reorder_product_variety      45.870895    33.329624   1.000000     419.000000
dow_entropy                   1.576796     0.279025   0.000000       1.945036
hour_entropy                  2.111670     0.303915   0.166683       2.996711
avg_order_hour               13.413162     1.804656   3.085470      22.338998
avg_order_dow                 2.765439     0.771699   0.000000       6.000000
orders_weekend_ratio          0.318931     0.219683   0.000000       1.000000
orders_morning_ratio          0.415131     0.212022   0.000000       1.000000
orders_evening_ratio          0.175703     0.156730   0.000000       1.000000
favorite_department_ratio     0.360958     0.142401   0.095618       1.000000
favorite_aisle_ratio          0.197575     0.106360   0.041570       1.000000

Constant and redundant features were removed prior to clustering, as they do not contribute to distance-based separation and may distort clustering results.

In [13]:
cols_to_drop = [
    'order_frequency',
    'min_items_per_order',
    'active_days_count'
]

clustering_df = clustering_df.drop(columns=cols_to_drop)

In [14]:
clustering_df.describe().T[['mean', 'std', 'min', 'max']]

                                  mean          std        min            max
total_orders                 28.774068    18.680644  12.000000      99.000000
avg_days_between_orders      10.793917     4.341299   0.284016      28.076923
max_days_between_orders      26.490515     6.052823   2.000000      30.000000
last_order_recency           12.212311     9.209482   0.000000      30.000000
avg_items_per_order           6.693737     3.204102   1.000000      37.908343
total_items                2447.219075  3372.532342  12.000000  137664.000000
reorder_ratio                 0.590082     0.157336   0.014493       0.989529
max_items_per_order          20.760080    10.645057   1.000000     145.000000
unique_products             101.476653    65.670172   1.000000     726.000000
unique_departments           12.805600     3.279852   1.000000      21.000000
unique_aisles                38.057748    16.383243   1.000000     102.000000
top_department_ratio          0.360958     0.142401   0.095618       1.000000
top_aisle_ratio               0.197575     0.106360   0.041570       1.000000
reorder_product_variety      45.870895    33.329624   1.000000     419.000000
dow_entropy                   1.576796     0.279025   0.000000       1.945036
hour_entropy                  2.111670     0.303915   0.166683       2.996711
avg_order_hour               13.413162     1.804656   3.085470      22.338998
avg_order_dow                 2.765439     0.771699   0.000000       6.000000
orders_weekend_ratio          0.318931     0.219683   0.000000       1.000000
orders_morning_ratio          0.415131     0.212022   0.000000       1.000000
orders_evening_ratio          0.175703     0.156730   0.000000       1.000000
favorite_department_ratio     0.360958     0.142401   0.095618       1.000000
favorite_aisle_ratio          0.197575     0.106360   0.041570       1.000000

In [15]:
clustering_df.to_csv("clustering_dataset_final.csv", index=False)

Since clustering algorithms are distance-based, features with larger numeric ranges may dominate the clustering process. Therefore, all features were standardized to ensure equal contribution.

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(clustering_df)

X_scaled_df = pd.DataFrame(
    X_scaled,
    columns=clustering_df.columns
)

X_scaled_df.head()

,total_orders,avg_days_between_orders,max_days_between_orders,last_order_recency,avg_items_per_order,total_items,reorder_ratio,max_items_per_order,unique_products,unique_departments,...,reorder_product_variety,dow_entropy,hour_entropy,avg_order_hour,avg_order_dow,orders_weekend_ratio,orders_morning_ratio,orders_evening_ratio,favorite_department_ratio,favorite_aisle_ratio
0,-0.790880,0.946415,0.579813,0.085531,0.580543,-0.231050,-0.719223,0.492243,0.007969,0.059271,...,-0.266158,-1.141710,-2.164482,-1.646936,-0.985248,-1.451787,2.371552,-1.121059,-0.806210,0.167450
1,-0.897944,-0.140995,-0.907105,0.302699,-0.702402,-0.609699,0.221935,-0.916870,-1.042742,-1.160303,...,-0.806221,-1.515573,-1.296910,1.628636,-2.273017,0.927685,-1.957976,0.256535,0.497613,0.172381
2,-0.469690,0.452255,0.579813,-0.565976,0.174368,-0.282644,0.507333,0.304361,-0.509772,-0.245622,...,-0.176147,0.100388,0.382807,0.120747,-1.344163,0.492771,0.033955,0.892186,-0.591707,-0.625303
3,-0.897944,-0.890981,-2.228810,-0.674560,-0.794483,-0.626008,0.329828,-1.010811,-1.103653,-0.550516,...,-0.986242,-2.500383,0.093829,0.954559,0.431941,2.819257,-0.560487,1.242066,-0.193994,-0.348638
4,-0.844412,3.038693,0.579813,-0.565976,1.369258,-0.035647,-1.692395,0.868006,0.617077,1.278846,...,-0.476183,-0.849936,-2.144973,-2.471832,1.698536,-0.801496,1.815244,-0.695696,-0.829361,-0.827863

In [17]:
X_scaled_df.describe().T[['mean', 'std']]

                                   mean       std
total_orders              -7.797832e-17  1.000006
avg_days_between_orders    7.977657e-17  1.000006
max_days_between_orders    1.791703e-16  1.000006
last_order_recency        -1.258770e-17  1.000006
avg_items_per_order        3.445269e-16  1.000006
total_items                8.173828e-19  1.000006
reorder_ratio             -1.057693e-16  1.000006
max_items_per_order       -3.310401e-17  1.000006
unique_products            7.192969e-18  1.000006
unique_departments         2.877188e-17  1.000006
unique_aisles              1.908589e-16  1.000006
top_department_ratio      -1.160684e-16  1.000006
top_aisle_ratio           -2.085961e-16  1.000006
reorder_product_variety   -8.337305e-18  1.000006
dow_entropy                5.594168e-16  1.000006
hour_entropy               8.345479e-17  1.000006
avg_order_hour             7.627817e-16  1.000006
avg_order_dow              3.997002e-16  1.000006
orders_weekend_ratio       1.618418e-17  1.000006
orders_morning_ratio      -1.968258e-16  1.000006
orders_evening_ratio      -4.577344e-18  1.000006
favorite_department_ratio -1.160684e-16  1.000006
favorite_aisle_ratio      -2.085961e-16  1.000006

In [20]:
X_scaled_df.to_csv("clustering_dataset_scaled.csv", index=False)

In addition to standard normalization, RobustScaler was tested as it is less sensitive to outliers and scales features based on median and interquartile range.

In [18]:
from sklearn.preprocessing import RobustScaler

robust_scaler = RobustScaler()

X_robust = robust_scaler.fit_transform(clustering_df)

X_robust_df = pd.DataFrame(
    X_robust,
    columns=clustering_df.columns
)

X_robust_df.head()

,total_orders,avg_days_between_orders,max_days_between_orders,last_order_recency,avg_items_per_order,total_items,reorder_ratio,max_items_per_order,unique_products,unique_departments,...,reorder_product_variety,dow_entropy,hour_entropy,avg_order_hour,avg_order_dow,orders_weekend_ratio,orders_morning_ratio,orders_evening_ratio,favorite_department_ratio,favorite_aisle_ratio
0,-0.421053,0.703460,0.000000,0.307692,0.579802,0.121123,-0.552072,0.500000,0.1625,0.00,...,-0.025641,-1.148363,-1.658499,-1.235208,-0.819274,-1.000546,1.714179,-0.663383,-0.493409,0.403531
1,-0.526316,-0.030955,-1.500000,0.461538,-0.437008,-0.414082,0.108709,-0.571429,-0.7000,-1.00,...,-0.487179,-1.460386,-1.007955,1.220064,-1.875624,0.766389,-1.336626,0.339230,0.549225,0.408543
2,-0.105263,0.369714,0.000000,-0.153846,0.257884,0.048198,0.309085,0.357143,-0.2625,-0.25,...,0.051282,-0.111715,0.251574,0.089796,-1.113690,0.443433,0.066989,0.801856,-0.321877,-0.402267
3,-0.526316,-0.537480,-2.833333,-0.230769,-0.509987,-0.437133,0.184460,-0.642857,-0.7500,-0.50,...,-0.641026,-2.282303,0.034885,0.714796,0.343239,2.171021,-0.351884,1.056498,-0.003836,-0.121050
4,-0.473684,2.116543,0.000000,-0.153846,1.204904,0.397318,-1.235329,0.785714,0.6625,1.00,...,-0.205128,-0.904849,-1.643870,-1.853525,1.382221,-0.517657,1.322176,-0.353804,-0.511922,-0.608161

In [21]:
X_robust_df.describe().T[['mean', 'std', 'min', 'max']]

                               mean       std       min        max
total_orders               0.356530  0.983192 -0.526316   4.052632
avg_days_between_orders    0.064270  0.675384 -1.570775   2.753020
max_days_between_orders   -0.584914  1.008804 -4.666667   0.000000
last_order_recency         0.247101  0.708422 -0.692308   1.615385
avg_items_per_order        0.119687  0.792563 -1.288710   7.840899
total_items                0.447703  1.413467 -0.572925  57.118609
reorder_ratio             -0.047110  0.702097 -2.615631   1.735390
max_items_per_order        0.125720  0.760361 -1.285714   9.000000
unique_products            0.155958  0.820877 -1.100000   7.962500
unique_departments        -0.048600  0.819963 -3.000000   2.000000
unique_aisles              0.002511  0.712315 -1.608696   2.782609
top_department_ratio       0.151297  0.799679 -1.338774   3.739958
top_aisle_ratio            0.233325  1.016461 -1.257579   7.901954
reorder_product_variety    0.201818  0.854606 -0.948718   9.769231
dow_entropy               -0.195498  0.834599 -4.911891   0.905955
hour_entropy              -0.035472  0.749850 -4.834341   2.148189
avg_order_hour            -0.000713  0.749575 -4.290382   3.706687
avg_order_dow             -0.011080  0.820300 -2.950682   3.427190
orders_weekend_ratio       0.077513  0.742579 -1.000546   2.379677
orders_morning_ratio       0.043063  0.704655 -1.336626   1.986876
orders_evening_ratio       0.152523  0.727804 -0.663383   3.980296
favorite_department_ratio  0.151297  0.799679 -1.338774   3.739958
favorite_aisle_ratio       0.233325  1.016461 -1.257579   7.901954

In [19]:
X_robust_df.to_csv("clustering_dataset_robust_scaled.csv", index=False)

In [22]:
comparison = pd.DataFrame({
    'std_scaled_std': X_scaled_df.std(),
    'robust_scaled_std': X_robust_df.std()
})

comparison.sort_values('std_scaled_std', ascending=False).head(10)

                         std_scaled_std  robust_scaled_std
avg_days_between_orders        1.000006           0.675384
avg_order_hour                 1.000006           0.749575
dow_entropy                    1.000006           0.834599
avg_order_dow                  1.000006           0.820300
last_order_recency             1.000006           0.708422
total_orders                   1.000006           0.983192
max_days_between_orders        1.000006           1.008804
reorder_ratio                  1.000006           0.702097
total_items                    1.000006           1.413467
avg_items_per_order            1.000006           0.792563